SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET client_min_messages = warning;
SET row_security = off;

CREATE DATABASE IF NOT EXISTS final;
DROP USER IF EXISTS final;
CREATE USER final WITH PASSWORD 'final';
GRANT ALL PRIVILEGES ON DATABASE final to final;

CREATE TABLE cityattributes(
  city CHARACTER VARYING(255),
  country CHARACTER VARYING(255),
  latitude DECIMAL(9,6),
  longitude DECIMAL(9,6)
);
CREATE TABLE humidity(
  dt DATETIME
  vancouver DECIMAL(4,1),
  portland DECIMAL(4,1),
  sanfran DECIMAL(4,1),
  seattle DECIMAL(4,1),
  losangeles DECIMAL(4,1),
  sandiego DECIMAL(4,1),
  lasvegas DECIMAL(4,1),
  phoenix DECIMAL(4,1),
  albuquerque DECIMAL(4,1),
  denver DECIMAL(4,1),
  sanantonio DECIMAL(4,1),
  dallas DECIMAL(4,1),
  houston DECIMAL(4,1),
  kansasct DECIMAL(4,1),
  minneapolis DECIMAL(4,1),
  stlouis DECIMAL(4,1),
  chicago DECIMAL(4,1),
  nashville DECIMAL(4,1),
  indianapolis DECIMAL(4,1),
  atlanta DECIMAL(4,1),
  detroit DECIMAL(4,1),
  jacksonville DECIMAL(4,1),
  charlotte DECIMAL(4,1),
  miami DECIMAL(4,1),
  pittsburgh DECIMAL(4,1),
  toronto DECIMAL(4,1),
  philiadelphia DECIMAL(4,1),
  newyork DECIMAL(4,1),
  montreal DECIMAL(4,1),
  boston DECIMAL(4,1),
  beersheba DECIMAL(4,1),
  telaviv DECIMAL(4,1),
  eilat DECIMAL(4,1),
  haifa DECIMAL(4,1),
  nahariyya DECIMAL(4,1),
  jerusalem DECIMAL(4,1)
);
CREATE TABLE pressure(
  dt DATETIME
  vancouver DECIMAL(5,1),
  portland DECIMAL(5,1),
  sanfran DECIMAL(5,1),
  seattle DECIMAL(5,1),
  losangeles DECIMAL(5,1),
  sandiego DECIMAL(5,1),
  lasvegas DECIMAL(5,1),
  phoenix DECIMAL(5,1),
  albuquerque DECIMAL(5,1),
  denver DECIMAL(5,1),
  sanantonio DECIMAL(5,1),
  dallas DECIMAL(5,1),
  houston DECIMAL(5,1),
  kansasct DECIMAL(5,1),
  minneapolis DECIMAL(5,1),
  stlouis DECIMAL(5,1),
  chicago DECIMAL(5,1),
  nashville DECIMAL(5,1),
  indianapolis DECIMAL(5,1),
  atlanta DECIMAL(5,1),
  detroit DECIMAL(5,1),
  jacksonville DECIMAL(5,1),
  charlotte DECIMAL(5,1),
  miami DECIMAL(5,1),
  pittsburgh DECIMAL(5,1),
  toronto DECIMAL(5,1),
  philiadelphia DECIMAL(5,1),
  newyork DECIMAL(5,1),
  montreal DECIMAL(5,1),
  boston DECIMAL(5,1),
  beersheba DECIMAL(5,1),
  telaviv DECIMAL(5,1),
  eilat DECIMAL(5,1),
  haifa DECIMAL(5,1),
  nahariyya DECIMAL(5,1),
  jerusalem DECIMAL(5,1)
);
CREATE TABLE temperature(
  dt DATETIME
  vancouver DECIMAL(12,9),
  portland DECIMAL(12,9),
  sanfran DECIMAL(12,9),
  seattle DECIMAL(12,9),
  losangeles DECIMAL(12,9),
  sandiego DECIMAL(12,9),
  lasvegas DECIMAL(12,9),
  phoenix DECIMAL(12,9),
  albuquerque DECIMAL(12,9),
  denver DECIMAL(12,9),
  sanantonio DECIMAL(12,9),
  dallas DECIMAL(12,9),
  houston DECIMAL(12,9),
  kansasct DECIMAL(12,9),
  minneapolis DECIMAL(12,9),
  stlouis DECIMAL(12,9),
  chicago DECIMAL(12,9),
  nashville DECIMAL(12,9),
  indianapolis DECIMAL(12,9),
  atlanta DECIMAL(12,9),
  detroit DECIMAL(12,9),
  jacksonville DECIMAL(12,9),
  charlotte DECIMAL(12,9),
  miami DECIMAL(12,9),
  pittsburgh DECIMAL(12,9),
  toronto DECIMAL(12,9),
  philiadelphia DECIMAL(12,9),
  newyork DECIMAL(12,9),
  montreal DECIMAL(12,9),
  boston DECIMAL(12,9),
  beersheba DECIMAL(12,9),
  telaviv DECIMAL(12,9),
  eilat DECIMAL(12,9),
  haifa DECIMAL(12,9),
  nahariyya DECIMAL(12,9),
  jerusalem DECIMAL(12,9)
);
CREATE TABLE discription(
  dt DATETIME
  vancouver CHARACTER VARYING(63),
  portland CHARACTER VARYING(63),
  sanfran CHARACTER VARYING(63),
  seattle CHARACTER VARYING(63),
  losangeles CHARACTER VARYING(63),
  sandiego CHARACTER VARYING(63),
  lasvegas CHARACTER VARYING(63),
  phoenix CHARACTER VARYING(63),
  albuquerque CHARACTER VARYING(63),
  denver CHARACTER VARYING(63),
  sanantonio CHARACTER VARYING(63),
  dallas CHARACTER VARYING(63),
  houston CHARACTER VARYING(63),
  kansasct CHARACTER VARYING(63),
  minneapolis CHARACTER VARYING(63),
  stlouis CHARACTER VARYING(63),
  chicago CHARACTER VARYING(63),
  nashville CHARACTER VARYING(63),
  indianapolis CHARACTER VARYING(63),
  atlanta CHARACTER VARYING(63),
  detroit CHARACTER VARYING(63),
  jacksonville CHARACTER VARYING(63),
  charlotte CHARACTER VARYING(63),
  miami CHARACTER VARYING(63),
  pittsburgh CHARACTER VARYING(63),
  toronto CHARACTER VARYING(63),
  philiadelphia CHARACTER VARYING(63),
  newyork CHARACTER VARYING(63),
  montreal CHARACTER VARYING(63),
  boston CHARACTER VARYING(63),
  beersheba CHARACTER VARYING(63),
  telaviv CHARACTER VARYING(63),
  eilat CHARACTER VARYING(63),
  haifa CHARACTER VARYING(63),
  nahariyya CHARACTER VARYING(63),
  jerusalem CHARACTER VARYING(63)
);
CREATE TABLE winddirection(
  dt DATETIME
  vancouver DECIMAL(4,1),
  portland DECIMAL(4,1),
  sanfran DECIMAL(4,1),
  seattle DECIMAL(4,1),
  losangeles DECIMAL(4,1),
  sandiego DECIMAL(4,1),
  lasvegas DECIMAL(4,1),
  phoenix DECIMAL(4,1),
  albuquerque DECIMAL(4,1),
  denver DECIMAL(4,1),
  sanantonio DECIMAL(4,1),
  dallas DECIMAL(4,1),
  houston DECIMAL(4,1),
  kansasct DECIMAL(4,1),
  minneapolis DECIMAL(4,1),
  stlouis DECIMAL(4,1),
  chicago DECIMAL(4,1),
  nashville DECIMAL(4,1),
  indianapolis DECIMAL(4,1),
  atlanta DECIMAL(4,1),
  detroit DECIMAL(4,1),
  jacksonville DECIMAL(4,1),
  charlotte DECIMAL(4,1),
  miami DECIMAL(4,1),
  pittsburgh DECIMAL(4,1),
  toronto DECIMAL(4,1),
  philiadelphia DECIMAL(4,1),
  newyork DECIMAL(4,1),
  montreal DECIMAL(4,1),
  boston DECIMAL(4,1),
  beersheba DECIMAL(4,1),
  telaviv DECIMAL(4,1),
  eilat DECIMAL(4,1),
  haifa DECIMAL(4,1),
  nahariyya DECIMAL(4,1),
  jerusalem DECIMAL(4,1)
);
CREATE TABLE windspeed(
  dt DATETIME
  vancouver DECIMAL(4,1),
  portland DECIMAL(4,1),
  sanfran DECIMAL(4,1),
  seattle DECIMAL(4,1),
  losangeles DECIMAL(4,1),
  sandiego DECIMAL(4,1),
  lasvegas DECIMAL(4,1),
  phoenix DECIMAL(4,1),
  albuquerque DECIMAL(4,1),
  denver DECIMAL(4,1),
  sanantonio DECIMAL(4,1),
  dallas DECIMAL(4,1),
  houston DECIMAL(4,1),
  kansasct DECIMAL(4,1),
  minneapolis DECIMAL(4,1),
  stlouis DECIMAL(4,1),
  chicago DECIMAL(4,1),
  nashville DECIMAL(4,1),
  indianapolis DECIMAL(4,1),
  atlanta DECIMAL(4,1),
  detroit DECIMAL(4,1),
  jacksonville DECIMAL(4,1),
  charlotte DECIMAL(4,1),
  miami DECIMAL(4,1),
  pittsburgh DECIMAL(4,1),
  toronto DECIMAL(4,1),
  philiadelphia DECIMAL(4,1),
  newyork DECIMAL(4,1),
  montreal DECIMAL(4,1),
  boston DECIMAL(4,1),
  beersheba DECIMAL(4,1),
  telaviv DECIMAL(4,1),
  eilat DECIMAL(4,1),
  haifa DECIMAL(4,1),
  nahariyya DECIMAL(4,1),
  jerusalem DECIMAL(4,1)
);
CREATE TABLE megawattphourly(
  dt DATETIME,
  aep DECIMAL(7,1),
  comed DECIMAL(7,1),
  dayton DECIMAL(7,1),
  deok DECIMAL(7,1),
  dom DECIMAL(7,1),
  duq DECIMAL(7,1),
  ekpc DECIMAL(7,1),
  fe DECIMAL(7,1),
  ni DECIMAL(7,1),
  pjme DECIMAL(7,1),
  pjmw DECIMAL(7,1),
  pjml DECIMAL(7,1)
);
